-------------------------------------------------------------------------------
Test set: org.dejava.component.i18n.test.message.SimpleMessageHandlerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.084 sec <<< FAILURE!
testGetMessageValidParams(org.dejava.component.i18n.test.message.SimpleMessageHandlerTest)  Time elapsed: 32 sec  <<< ERROR!
org.dejava.component.test.exception.parametric.atomic.AtomParametricTestException: Um erro inesperado foi encontrado. Tente novamente em alguns instantes.
	at org.dejava.component.test.runner.statement.ParametricTestWrapper.evaluate(ParametricTestWrapper.java:76)
	at org.dejava.component.test.runner.JUnitParametricRunner.runParametricTest(JUnitParametricRunner.java:314)
	at org.dejava.component.test.runner.JUnitParametricRunner.runChild(JUnitParametricRunner.java:350)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.dejava.component.i18n.message.exception.MessageNotFoundException: Um erro inesperado foi encontrado. Tente novamente em alguns instantes.
	at org.dejava.component.i18n.message.handler.impl.SimpleMessageHandler.getMessage(SimpleMessageHandler.java:364)
	at org.dejava.component.i18n.message.handler.impl.SimpleMessageHandler.getMessage(SimpleMessageHandler.java:390)
	at org.dejava.component.i18n.message.handler.impl.SimpleMessageHandler.getMessage(SimpleMessageHandler.java:415)
	at org.dejava.component.i18n.message.handler.impl.SimpleMessageCommand.getMessage(SimpleMessageCommand.java:203)
	at org.dejava.component.i18n.test.message.SimpleMessageHandlerTest.testGetMessageValidParams(SimpleMessageHandlerTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.dejava.component.test.runner.statement.ParametricTestMethodInvoker.evaluate(ParametricTestMethodInvoker.java:32)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:110)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)

